# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sm_cipher_tools.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sm_cipher_tools(object):
    def setupUi(self, sm_cipher_tools):
        sm_cipher_tools.setObjectName("sm_cipher_tools")
        sm_cipher_tools.resize(644, 640)
        icon = QtGui.QIcon.fromTheme("ahdms")
        sm_cipher_tools.setWindowIcon(icon)
        sm_cipher_tools.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(sm_cipher_tools)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.result_textEdit = QtWidgets.QTextEdit(sm_cipher_tools)
        self.result_textEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_textEdit.setObjectName("result_textEdit")
        self.gridLayout.addWidget(self.result_textEdit, 21, 0, 1, 11)
        self.mode_comboBox = QtWidgets.QComboBox(sm_cipher_tools)
        self.mode_comboBox.setObjectName("mode_comboBox")
        self.mode_comboBox.addItem("")
        self.mode_comboBox.addItem("")
        self.mode_comboBox.addItem("")
        self.mode_comboBox.addItem("")
        self.gridLayout.addWidget(self.mode_comboBox, 17, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.sm4_decrypt_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.sm4_decrypt_Button.setObjectName("sm4_decrypt_Button")
        self.gridLayout.addWidget(self.sm4_decrypt_Button, 17, 2, 1, 1)
        self.signature_value = QtWidgets.QLineEdit(sm_cipher_tools)
        self.signature_value.setText("")
        self.signature_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.signature_value.setObjectName("signature_value")
        self.gridLayout.addWidget(self.signature_value, 9, 1, 1, 10)
        self.label_3 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.pubkall_LE = QtWidgets.QLineEdit(sm_cipher_tools)
        self.pubkall_LE.setText("")
        self.pubkall_LE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pubkall_LE.setObjectName("pubkall_LE")
        self.gridLayout.addWidget(self.pubkall_LE, 3, 1, 1, 10)
        self.label_6 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.pubky_LE = QtWidgets.QLineEdit(sm_cipher_tools)
        self.pubky_LE.setText("")
        self.pubky_LE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pubky_LE.setObjectName("pubky_LE")
        self.gridLayout.addWidget(self.pubky_LE, 2, 1, 1, 10)
        self.label_5 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.decrypt_result = QtWidgets.QLineEdit(sm_cipher_tools)
        self.decrypt_result.setText("")
        self.decrypt_result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.decrypt_result.setObjectName("decrypt_result")
        self.gridLayout.addWidget(self.decrypt_result, 11, 1, 1, 10)
        self.label_4 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.pubkx_LE = QtWidgets.QLineEdit(sm_cipher_tools)
        self.pubkx_LE.setText("")
        self.pubkx_LE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pubkx_LE.setObjectName("pubkx_LE")
        self.gridLayout.addWidget(self.pubkx_LE, 1, 1, 1, 10)
        self.label_12 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.plaintext_hex = QtWidgets.QLineEdit(sm_cipher_tools)
        self.plaintext_hex.setText("")
        self.plaintext_hex.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.plaintext_hex.setObjectName("plaintext_hex")
        self.gridLayout.addWidget(self.plaintext_hex, 5, 1, 1, 10)
        self.label_10 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.pad_checkBox = QtWidgets.QCheckBox(sm_cipher_tools)
        self.pad_checkBox.setObjectName("pad_checkBox")
        self.gridLayout.addWidget(self.pad_checkBox, 17, 3, 1, 1)
        self.sm4_encrypt_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.sm4_encrypt_Button.setObjectName("sm4_encrypt_Button")
        self.gridLayout.addWidget(self.sm4_encrypt_Button, 17, 1, 1, 1)
        self.id_iv = QtWidgets.QLineEdit(sm_cipher_tools)
        self.id_iv.setText("")
        self.id_iv.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.id_iv.setObjectName("id_iv")
        self.gridLayout.addWidget(self.id_iv, 7, 1, 1, 10)
        self.label_11 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.e_LE = QtWidgets.QLineEdit(sm_cipher_tools)
        self.e_LE.setText("")
        self.e_LE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.e_LE.setObjectName("e_LE")
        self.gridLayout.addWidget(self.e_LE, 8, 1, 1, 10)
        self.sm3_hash = QtWidgets.QLineEdit(sm_cipher_tools)
        self.sm3_hash.setText("")
        self.sm3_hash.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sm3_hash.setObjectName("sm3_hash")
        self.gridLayout.addWidget(self.sm3_hash, 6, 1, 1, 10)
        self.privkey = QtWidgets.QLineEdit(sm_cipher_tools)
        self.privkey.setText("")
        self.privkey.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.privkey.setObjectName("privkey")
        self.gridLayout.addWidget(self.privkey, 0, 1, 1, 10)
        self.plaintext = QtWidgets.QLineEdit(sm_cipher_tools)
        self.plaintext.setText("")
        self.plaintext.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.plaintext.setObjectName("plaintext")
        self.gridLayout.addWidget(self.plaintext, 4, 1, 1, 10)
        self.label_2 = QtWidgets.QLabel(sm_cipher_tools)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.encrypt_result = QtWidgets.QLineEdit(sm_cipher_tools)
        self.encrypt_result.setText("")
        self.encrypt_result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.encrypt_result.setObjectName("encrypt_result")
        self.gridLayout.addWidget(self.encrypt_result, 10, 1, 1, 10)
        self.label = QtWidgets.QLabel(sm_cipher_tools)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.clear_input_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.clear_input_Button.setObjectName("clear_input_Button")
        self.gridLayout.addWidget(self.clear_input_Button, 12, 3, 1, 2)
        self.sm2_decrypt_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.sm2_decrypt_Button.setSizeIncrement(QtCore.QSize(0, 0))
        self.sm2_decrypt_Button.setObjectName("sm2_decrypt_Button")
        self.gridLayout.addWidget(self.sm2_decrypt_Button, 14, 4, 1, 1)
        self.sm3_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.sm3_Button.setObjectName("sm3_Button")
        self.gridLayout.addWidget(self.sm3_Button, 14, 1, 1, 1)
        self.sm2_encrypt_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.sm2_encrypt_Button.setObjectName("sm2_encrypt_Button")
        self.gridLayout.addWidget(self.sm2_encrypt_Button, 14, 3, 1, 1)
        self.gen_keypair_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.gen_keypair_Button.setObjectName("gen_keypair_Button")
        self.gridLayout.addWidget(self.gen_keypair_Button, 14, 2, 1, 1)
        self.sm2_sign_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.sm2_sign_Button.setObjectName("sm2_sign_Button")
        self.gridLayout.addWidget(self.sm2_sign_Button, 14, 5, 1, 1)
        self.sm2_verify_Button = QtWidgets.QPushButton(sm_cipher_tools)
        self.sm2_verify_Button.setObjectName("sm2_verify_Button")
        self.gridLayout.addWidget(self.sm2_verify_Button, 14, 6, 1, 1)

        self.retranslateUi(sm_cipher_tools)
        QtCore.QMetaObject.connectSlotsByName(sm_cipher_tools)

    def retranslateUi(self, sm_cipher_tools):
        _translate = QtCore.QCoreApplication.translate
        sm_cipher_tools.setWindowTitle(_translate("sm_cipher_tools", "sm_cipher_tools"))
        self.mode_comboBox.setItemText(0, _translate("sm_cipher_tools", "ECB"))
        self.mode_comboBox.setItemText(1, _translate("sm_cipher_tools", "CBC"))
        self.mode_comboBox.setItemText(2, _translate("sm_cipher_tools", "CFB"))
        self.mode_comboBox.setItemText(3, _translate("sm_cipher_tools", "OFB"))
        self.label_8.setText(_translate("sm_cipher_tools", "ID/IV(HEX)："))
        self.sm4_decrypt_Button.setText(_translate("sm_cipher_tools", "SM4解密"))
        self.label_3.setText(_translate("sm_cipher_tools", "公钥Y(HEX)："))
        self.label_6.setText(_translate("sm_cipher_tools", "SM3 摘要："))
        self.label_5.setText(_translate("sm_cipher_tools", "原文："))
        self.label_4.setText(_translate("sm_cipher_tools", "原文(HEX)："))
        self.label_12.setText(_translate("sm_cipher_tools", "e值："))
        self.label_7.setText(_translate("sm_cipher_tools", "签名值："))
        self.label_9.setText(_translate("sm_cipher_tools", "加密结果："))
        self.label_10.setText(_translate("sm_cipher_tools", "公钥(HEX)："))
        self.pad_checkBox.setText(_translate("sm_cipher_tools", "PAD"))
        self.sm4_encrypt_Button.setText(_translate("sm_cipher_tools", "SM4加密"))
        self.label_11.setText(_translate("sm_cipher_tools", "解密结果："))
        self.label_2.setText(_translate("sm_cipher_tools", "公钥X(HEX)："))
        self.label.setText(_translate("sm_cipher_tools", "私钥KEY(HEX)："))
        self.clear_input_Button.setText(_translate("sm_cipher_tools", "清空输入数据"))
        self.sm2_decrypt_Button.setText(_translate("sm_cipher_tools", "SM2解密"))
        self.sm3_Button.setText(_translate("sm_cipher_tools", "SM3摘要"))
        self.sm2_encrypt_Button.setText(_translate("sm_cipher_tools", "SM2加密"))
        self.gen_keypair_Button.setText(_translate("sm_cipher_tools", "密钥对生成"))
        self.sm2_sign_Button.setText(_translate("sm_cipher_tools", "SM2签名"))
        self.sm2_verify_Button.setText(_translate("sm_cipher_tools", "SM2验签"))

